# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: davdunc
name: personal.davdunc
version: 0.1.1
readme: README.md
authors:
  - davdunc
description: A collection of automation tools for davdunc's personal preferences
license_file: LICENSE

tags:
  - personal
  - non-production

dependencies:
  community.general: ">=3.0.0"

repository: https://github.com/davdunc/personal.davdunc

documentation: https://github.com/davdunc/davdunc.personal.davdunc/tree/main/docs
homepage: https://github.com/davdunc/personal.davdunc

issues: https://github.com/davdunc/personal.davdunc/issues

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
