# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: personal.davdunc
version: 0.1.0
readme: README.md
authors:
  - DAVID DUNCAN (github.com/davdunc)
description: null
license_file: LICENSE
tags:
  - personal
  - non-production
repository: https://github.com/davdunc/personal.davdunc
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/davdunc/personal.davdunc
issues: https://github.com/davdunc/personal.davdunc/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
